title:
  de: Standard Seite
  en: Default page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          main: fields/layouts
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files

