title: Site
tabs:
  dashboard:
    label: panel.site.tabs.dashboard.label
    icon: dashboard
    sections:
      mainnavigation:
        label: panel.site.sections.mainmenu.label
        type: pages
        layout: cards
        text: '{{ page.title }}'
        info: '/{{ page.isHomePage() ? "" : page.uid}}'
        status: listed
        image: false
      settings:
        type: fields
        fields:
          footermenu:
            label: panel.site.fields.footermenu.label
            type: pages
            width: 1/2
            image: false
          privacypage:
            label: panel.site.fields.privacypage.label
            type: pages
            max: 1
            width: 1/2
            image: false
      pages:
        label: panel.site.sections.pages.label
        type: pages
        status: unlisted
        sortBy: title
        template:
          - home
          - default
          - error
          - thanks
        image: false
      drafts:
        label: panel.site.sections.drafts.label
        type: pages
        status: draft
        sortBy: title
        template:
          - default
        image: false
  seo: seo/site
  files: tabs/files
