title: Site
tabs:
  dashboard:
    label: panel.site.tabs.dashboard.label
    icon: dashboard
    sections:
      pages:
        label: panel.site.sections.pages.label
        type: pages
        status: published
        template:
          - home
          - default
          - error
          - thanks
        image: false
      drafts:
        label: panel.site.sections.drafts.label
        type: pages
        status: draft
        sortBy: title
        template:
          - default
        image: false
  headerfooter:
    label:  panel.site.tabs.headerfooter.label
    icon: header-footer
    sections:
      fields:
        type: fields
        fields:
          mainmenu:
            label: panel.site.fields.mainmenu.label
            type: pages
            width: 1/2
            image: false
          footermenu:
            label: panel.site.fields.footermenu.label
            type: pages
            width: 1/2
            image: false
  seo: seo/site
